# Generated by Django 5.1 on 2025-10-05 18:50

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dingtalk', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='规则名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='说明')),
                ('workday_start', models.TimeField(verbose_name='工作开始时间')),
                ('workday_end', models.TimeField(verbose_name='工作结束时间')),
                ('allow_late_minutes', models.PositiveIntegerField(default=0, verbose_name='允许迟到分钟数')),
                ('allow_early_minutes', models.PositiveIntegerField(default=0, verbose_name='允许早退分钟数')),
                ('absence_minutes', models.PositiveIntegerField(default=60, help_text='超过该分钟数记为缺勤', verbose_name='记缺勤阈值')),
                ('overtime_start_minutes', models.PositiveIntegerField(default=30, help_text='超过下班时间多少分钟计为加班', verbose_name='加班判定阈值')),
                ('weekend_as_workday', models.BooleanField(default=False, verbose_name='周末算工作日')),
                ('custom_workdays', models.JSONField(blank=True, default=list, help_text='例如 [1,2,3,4,5] 表示周一至周五', verbose_name='自定义工作日')),
            ],
            options={
                'verbose_name': '考勤规则',
                'verbose_name_plural': '考勤规则',
                'db_table': 'hr_attendance_rule',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PayrollRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='规则名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='说明')),
                ('overtime_rate', models.DecimalField(decimal_places=2, default=Decimal('1.5'), max_digits=6, verbose_name='加班倍数')),
                ('late_penalty_per_minute', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='迟到扣款/分钟')),
                ('absence_penalty_per_day', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='缺勤扣款/天')),
                ('tax_rate', models.DecimalField(decimal_places=4, default=Decimal('0.1'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='个税比例')),
                ('other_allowance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='额外补贴')),
            ],
            options={
                'verbose_name': '薪资规则',
                'verbose_name_plural': '薪资规则',
                'db_table': 'hr_payroll_rule',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=255, verbose_name='部门名称')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='部门编码')),
                ('config_id', models.CharField(blank=True, default='', max_length=64, verbose_name='配置ID')),
                ('description', models.TextField(blank=True, default='', verbose_name='说明')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='附加信息')),
                ('status', models.SmallIntegerField(choices=[(1, '启用'), (0, '停用')], default=1, verbose_name='状态')),
                ('ding_department', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_department', to='dingtalk.dingtalkdepartment', verbose_name='钉钉部门')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='hr.department', verbose_name='上级部门')),
            ],
            options={
                'verbose_name': '人力资源部门',
                'verbose_name_plural': '人力资源部门',
                'db_table': 'hr_department',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('config_id', models.CharField(blank=True, default='', max_length=64, verbose_name='配置ID')),
                ('name', models.CharField(max_length=255, verbose_name='姓名')),
                ('job_number', models.CharField(max_length=64, unique=True, verbose_name='工号')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='邮箱')),
                ('phone', models.CharField(blank=True, default='', max_length=32, verbose_name='电话')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='职位')),
                ('employment_type', models.SmallIntegerField(choices=[(1, '全职'), (2, '兼职'), (3, '实习'), (4, '外包')], default=1, verbose_name='雇佣类型')),
                ('employment_status', models.SmallIntegerField(choices=[(1, '试用'), (2, '在职'), (3, '停薪留职'), (4, '离职')], default=1, verbose_name='雇佣状态')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='入职日期')),
                ('regular_date', models.DateField(blank=True, null=True, verbose_name='转正日期')),
                ('separation_date', models.DateField(blank=True, null=True, verbose_name='离职日期')),
                ('base_salary', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='基础工资')),
                ('allowance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='固定补贴')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='附加信息')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='hr.department', verbose_name='所属部门')),
                ('ding_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_employee', to='dingtalk.dingtalkuser', verbose_name='钉钉用户')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_profile', to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '员工信息',
                'verbose_name_plural': '员工信息',
                'db_table': 'hr_employee',
                'ordering': ('job_number',),
            },
        ),
        migrations.CreateModel(
            name='AttendanceSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('period_start', models.DateField(verbose_name='统计开始')),
                ('period_end', models.DateField(verbose_name='统计结束')),
                ('work_days', models.PositiveIntegerField(default=0, verbose_name='应出勤天数')),
                ('present_days', models.PositiveIntegerField(default=0, verbose_name='实际出勤天数')),
                ('late_minutes', models.PositiveIntegerField(default=0, verbose_name='迟到分钟数')),
                ('early_leave_minutes', models.PositiveIntegerField(default=0, verbose_name='早退分钟数')),
                ('absence_days', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='缺勤天数')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='加班小时')),
                ('detail', models.JSONField(blank=True, default=dict, verbose_name='明细')),
                ('status', models.SmallIntegerField(choices=[(1, '待确认'), (2, '已确认')], default=1, verbose_name='状态')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='summaries', to='hr.attendancerule', verbose_name='规则')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_summaries', to='hr.employee', verbose_name='员工')),
            ],
            options={
                'verbose_name': '考勤统计',
                'verbose_name_plural': '考勤统计',
                'db_table': 'hr_attendance_summary',
                'ordering': ('-period_start', 'employee__job_number'),
            },
        ),
        migrations.CreateModel(
            name='PayrollRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('period_start', models.DateField(verbose_name='发薪开始')),
                ('period_end', models.DateField(verbose_name='发薪结束')),
                ('gross_salary', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='应发工资')),
                ('deductions', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='扣减合计')),
                ('net_salary', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='实发工资')),
                ('tax', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='个税')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('detail', models.JSONField(blank=True, default=dict, verbose_name='明细')),
                ('status', models.SmallIntegerField(choices=[(1, '待发放'), (2, '已确认'), (3, '已发放')], default=1, verbose_name='状态')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='发放时间')),
                ('attendance_summary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_records', to='hr.attendancesummary', verbose_name='关联考勤')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_records', to='hr.employee', verbose_name='员工')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_records', to='hr.payrollrule', verbose_name='规则')),
            ],
            options={
                'verbose_name': '薪资记录',
                'verbose_name_plural': '薪资记录',
                'db_table': 'hr_payroll_record',
                'ordering': ('-period_start', 'employee__job_number'),
            },
        ),
        migrations.AddConstraint(
            model_name='attendancesummary',
            constraint=models.UniqueConstraint(fields=('employee', 'period_start', 'period_end'), name='uniq_employee_period'),
        ),
    ]
