# Generated by Django 5.1 on 2025-10-04 11:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0011_alter_deptinfo_options_alter_menu_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DingTalkConfig',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.CharField(default='default', editable=False, max_length=32, primary_key=True, serialize=False, verbose_name='配置ID')),
                ('app_key', models.CharField(blank=True, default='', max_length=128, verbose_name='App Key')),
                ('app_secret', models.CharField(blank=True, default='', max_length=256, verbose_name='App Secret')),
                ('agent_id', models.CharField(blank=True, default='', max_length=64, verbose_name='Agent ID')),
                ('enabled', models.BooleanField(default=False, verbose_name='是否启用')),
                ('sync_users', models.BooleanField(default=True, verbose_name='同步用户')),
                ('sync_departments', models.BooleanField(default=True, verbose_name='同步部门')),
                ('callback_url', models.CharField(blank=True, default='', max_length=512, verbose_name='回调地址')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('access_token', models.CharField(blank=True, default='', max_length=512, verbose_name='访问令牌')),
                ('access_token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='令牌过期时间')),
                ('last_sync_time', models.DateTimeField(blank=True, null=True, verbose_name='最近同步时间')),
                ('last_user_sync_time', models.DateTimeField(blank=True, null=True, verbose_name='用户最近同步时间')),
                ('last_dept_sync_time', models.DateTimeField(blank=True, null=True, verbose_name='部门最近同步时间')),
                ('last_sync_status', models.CharField(blank=True, default='', max_length=32, verbose_name='最近同步状态')),
                ('last_sync_message', models.CharField(blank=True, default='', max_length=512, verbose_name='最近同步信息')),
                ('last_user_sync_count', models.IntegerField(default=0, verbose_name='最近同步用户数量')),
                ('last_dept_sync_count', models.IntegerField(default=0, verbose_name='最近同步部门数量')),
            ],
            options={
                'verbose_name': '钉钉配置',
                'verbose_name_plural': '钉钉配置',
            },
        ),
        migrations.CreateModel(
            name='DingTalkDepartment',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('dept_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='部门ID')),
                ('name', models.CharField(max_length=255, verbose_name='部门名称')),
                ('parent_id', models.BigIntegerField(blank=True, null=True, verbose_name='父级部门ID')),
                ('order', models.BigIntegerField(blank=True, null=True, verbose_name='排序')),
                ('leader_userid', models.CharField(blank=True, default='', max_length=128, verbose_name='负责人')),
                ('dept_type', models.CharField(blank=True, default='', max_length=64, verbose_name='部门类型')),
                ('source_info', models.JSONField(blank=True, default=dict, verbose_name='原始数据')),
            ],
            options={
                'verbose_name': '钉钉部门',
                'verbose_name_plural': '钉钉部门',
                'ordering': ('dept_id',),
            },
        ),
        migrations.CreateModel(
            name='DingTalkSyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('operation', models.CharField(choices=[('test_connection', '测试连接'), ('sync_departments', '同步部门'), ('sync_users', '同步用户'), ('full_sync', '全量同步')], max_length=32, verbose_name='操作类型')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败')], max_length=16, verbose_name='状态')),
                ('message', models.CharField(blank=True, default='', max_length=512, verbose_name='消息')),
                ('detail', models.TextField(blank=True, default='', verbose_name='详细信息')),
                ('stats', models.JSONField(blank=True, default=dict, verbose_name='统计数据')),
            ],
            options={
                'verbose_name': '钉钉同步日志',
                'verbose_name_plural': '钉钉同步日志',
                'ordering': ('-create_time',),
            },
        ),
        migrations.CreateModel(
            name='DingTalkUser',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('userid', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='用户ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='姓名')),
                ('mobile', models.CharField(blank=True, default='', max_length=64, verbose_name='手机号')),
                ('email', models.CharField(blank=True, default='', max_length=255, verbose_name='邮箱')),
                ('active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('job_number', models.CharField(blank=True, default='', max_length=128, verbose_name='工号')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='职位')),
                ('dept_ids', models.JSONField(blank=True, default=list, verbose_name='所属部门ID列表')),
                ('unionid', models.CharField(blank=True, default='', max_length=255, verbose_name='UnionID')),
                ('remark', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('source_info', models.JSONField(blank=True, default=dict, verbose_name='原始数据')),
            ],
            options={
                'verbose_name': '钉钉用户',
                'verbose_name_plural': '钉钉用户',
                'ordering': ('userid',),
            },
        ),
    ]
