# Generated by Django 5.1 on 2024-10-31 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_is_active_user_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户表', 'verbose_name_plural': '用户表'},
        ),
    ]
