# Generated by Django 5.1 on 2025-10-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='backup_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='备用邮箱'),
        ),
        migrations.AddField(
            model_name='user',
            name='login_notifier_enabled',
            field=models.BooleanField(default=True, verbose_name='登录提醒开关'),
        ),
        migrations.AddField(
            model_name='user',
            name='password_strength',
            field=models.CharField(default='unknown', max_length=16, verbose_name='密码强度'),
        ),
        migrations.AddField(
            model_name='user',
            name='password_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='密码最后更新时间'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='手机号'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_verified',
            field=models.BooleanField(default=False, verbose_name='手机号是否已验证'),
        ),
        migrations.AddField(
            model_name='user',
            name='security_answer_hash',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='密保答案哈希'),
        ),
        migrations.AddField(
            model_name='user',
            name='security_question',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='密保问题'),
        ),
        migrations.AddField(
            model_name='user',
            name='security_question_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='密保更新时间'),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_enabled',
            field=models.BooleanField(default=False, verbose_name='是否开启两步验证'),
        ),
    ]
